import Db

/-!
# `0001_initial`

The whole of orchestra's schema as one migration, generated by `Db.Migration.planSteps`/`render`
against `Orchestra.Store.target` and committed as source, so that the schema a deployment gets is
a function of the code rather than of the database the code happens to find.

Generated; edit only to fix it up by hand, and never after a deployment has recorded it — a
schema change is the next migration, not a rewrite of this one.
-/

namespace Orchestra.Store.Migrations

/-- Generated by `makemigrations`; edit freely. -/
def migration_0001_initial : Db.Migration.Migration where
  name := "0001_initial"
  steps := [
    .createTable "concert_run"
      { columns := .ofList
          [("name", { type := .text, nullable := true }),
           ("started_at", { type := .text, nullable := false }),
           ("workflow_file", { type := .text, nullable := true }),
           ("status", { type := .text, nullable := false }),
           ("finished_at", { type := .text, nullable := true }),
           ("id", { type := .text, nullable := false })],
        primaryKey := ["id"] },
    .createTable "queue_entry"
      { columns := .ofList
          [("prompt", { type := .text, nullable := false }),
           ("tools", { type := .text, nullable := true }),
           ("triage_add_labels", { type := .text, nullable := false }),
           ("read_only", { type := .bool, nullable := false }),
           ("model", { type := .text, nullable := true }),
           ("backend", { type := .text, nullable := true }),
           ("listener_name", { type := .text, nullable := true }),
           ("task_id", { type := .text, nullable := true }),
           ("slot", { type := .int, nullable := true }),
           ("output_json", { type := .text, nullable := true }),
           ("input_json", { type := .text, nullable := true }),
           ("role", { type := .text, nullable := true }),
           ("upstream", { type := .text, nullable := true }),
           ("auth_sources", { type := .text, nullable := false }),
           ("triage_remove_labels", { type := .text, nullable := false }),
           ("input_type", { type := .text, nullable := false }),
           ("agent", { type := .text, nullable := true }),
           ("project_id", { type := .text, nullable := true }),
           ("mode", { type := .text, nullable := false }),
           ("continues_from", { type := .text, nullable := true }),
           ("concert_id", { type := .text, nullable := true }),
           ("created_at", { type := .text, nullable := false }),
           ("fork", { type := .text, nullable := true }),
           ("budget", { type := .float, nullable := true }),
           ("auth_source", { type := .text, nullable := true }),
           ("series", { type := .text, nullable := true }),
           ("scope_root", { type := .text, nullable := true }),
           ("identity", { type := .text, nullable := true }),
           ("prepend_prompt", { type := .text, nullable := true }),
           ("spawned_by", { type := .text, nullable := true }),
           ("priority", { type := .int, nullable := false }),
           ("output_type", { type := .text, nullable := false }),
           ("id", { type := .text, nullable := false }),
           ("auth_mode", { type := .text, nullable := true }),
           ("spawn_policy", { type := .text, nullable := true }),
           ("pr_labels", { type := .text, nullable := false }),
           ("memory", { type := .text, nullable := false }),
           ("goal", { type := .text, nullable := true }),
           ("issue_id", { type := .text, nullable := true }),
           ("status", { type := .text, nullable := false }),
           ("concert_step_key", { type := .text, nullable := true }),
           ("config_path", { type := .text, nullable := true }),
           ("issue_number", { type := .int, nullable := true }),
           ("system_prompt", { type := .text, nullable := true })],
        primaryKey := ["id"] },
    .createTable "usage_window"
      { columns := .ofList
          [("reset_epoch", { type := .int, nullable := true }),
           ("scope", { type := .text, nullable := true }),
           ("start_epoch", { type := .int, nullable := false }),
           ("kind", { type := .text, nullable := false }),
           ("peak_percent", { type := .int, nullable := false }),
           ("label", { type := .text, nullable := false }),
           ("last_epoch", { type := .int, nullable := false }),
           ("backend", { type := .text, nullable := false }),
           ("last_percent", { type := .int, nullable := false }),
           ("samples", { type := .int, nullable := false }),
           ("id", { type := .int, nullable := false, autoIncrement := true })],
        primaryKey := ["id"] },
    .createTable "series"
      { columns := .ofList
          [("name", { type := .text, nullable := false }),
           ("latest_task_id", { type := .text, nullable := false })],
        primaryKey := ["name"] },
    .createTable "interactive_session"
      { columns := .ofList
          [("agent_started", { type := .bool, nullable := false }),
           ("created_at", { type := .text, nullable := false }),
           ("tools", { type := .text, nullable := true }),
           ("fork", { type := .text, nullable := false }),
           ("budget", { type := .float, nullable := false }),
           ("agent_session_id", { type := .text, nullable := true }),
           ("error", { type := .text, nullable := true }),
           ("identity", { type := .text, nullable := true }),
           ("model", { type := .text, nullable := true }),
           ("cost_usd", { type := .float, nullable := false }),
           ("backend", { type := .text, nullable := false }),
           ("slot", { type := .int, nullable := false }),
           ("id", { type := .text, nullable := false }),
           ("title", { type := .text, nullable := true }),
           ("ended_at", { type := .text, nullable := true }),
           ("resumed_from", { type := .text, nullable := true }),
           ("upstream", { type := .text, nullable := false }),
           ("turn_count", { type := .int, nullable := false }),
           ("status", { type := .text, nullable := false }),
           ("system_prompt", { type := .text, nullable := true }),
           ("last_activity_at", { type := .text, nullable := false }),
           ("last_event_seq", { type := .int, nullable := false })],
        primaryKey := ["id"] },
    .createTable "interactive_event"
      { columns := .ofList
          [("session_id", { type := .text, nullable := false }),
           ("seq", { type := .int, nullable := false }),
           ("occurred_at", { type := .text, nullable := false }),
           ("doc", { type := .text, nullable := false })],
        primaryKey := ["session_id", "seq"] },
    .createTable "usage_source"
      { columns := .ofList
          [("blocks", { type := .text, nullable := false }),
           ("limits", { type := .text, nullable := false }),
           ("label", { type := .text, nullable := false }),
           ("last_error", { type := .text, nullable := true }),
           ("last_used_tick", { type := .int, nullable := true }),
           ("backend", { type := .text, nullable := false }),
           ("poll_after", { type := .int, nullable := true }),
           ("fetched_epoch", { type := .int, nullable := true })],
        primaryKey := ["backend", "label"] },
    .createTable "listener_state"
      { columns := .ofList
          [("name", { type := .text, nullable := false }),
           ("last_checked", { type := .text, nullable := false }),
           ("processed_ids", { type := .text, nullable := false }),
           ("enabled", { type := .bool, nullable := false }),
           ("dispatches", { type := .text, nullable := false })],
        primaryKey := ["name"] },
    .createTable "task"
      { columns := .ofList
          [("created_at", { type := .text, nullable := false }),
           ("fork", { type := .text, nullable := true }),
           ("prompt", { type := .text, nullable := false }),
           ("budget", { type := .float, nullable := true }),
           ("series", { type := .text, nullable := true }),
           ("identity", { type := .text, nullable := true }),
           ("prepend_prompt", { type := .text, nullable := true }),
           ("model", { type := .text, nullable := true }),
           ("priority", { type := .int, nullable := false }),
           ("backend", { type := .text, nullable := true }),
           ("id", { type := .text, nullable := false }),
           ("session_id", { type := .text, nullable := true }),
           ("role", { type := .text, nullable := true }),
           ("goal", { type := .text, nullable := true }),
           ("upstream", { type := .text, nullable := true }),
           ("agent", { type := .text, nullable := true }),
           ("issue_id", { type := .text, nullable := true }),
           ("status", { type := .text, nullable := false }),
           ("project_id", { type := .text, nullable := true }),
           ("system_prompt", { type := .text, nullable := true }),
           ("mode", { type := .text, nullable := false }),
           ("continues_from", { type := .text, nullable := true })],
        primaryKey := ["id"] },
    .createTable "legacy_import"
      { columns := .ofList
          [("records", { type := .int, nullable := false }),
           ("store", { type := .text, nullable := false }),
           ("imported_at", { type := .text, nullable := false })],
        primaryKey := ["store"] },
    .createIndex "concert_run" { name := "idx_concert_run_started_at_id", keys := [{ column := "started_at", direction := .desc }, { column := "id", direction := .desc }] },
    .createIndex "interactive_session" { name := "idx_interactive_session_created_at_id", keys := [{ column := "created_at", direction := .desc }, { column := "id", direction := .desc }] },
    .createIndex "interactive_session" { name := "idx_interactive_session_status", keys := [{ column := "status" }] },
    .createIndex "queue_entry" { name := "idx_queue_entry_created_at_id", keys := [{ column := "created_at", direction := .desc }, { column := "id", direction := .desc }] },
    .createIndex "queue_entry" { name := "idx_queue_entry_status", keys := [{ column := "status" }] },
    .createIndex "queue_entry" { name := "idx_queue_entry_task_id", keys := [{ column := "task_id" }] },
    .createIndex "queue_entry" { name := "idx_queue_entry_concert_id", keys := [{ column := "concert_id" }] },
    .createIndex "queue_entry" { name := "idx_queue_entry_spawned_by", keys := [{ column := "spawned_by" }] },
    .createIndex "queue_entry" { name := "idx_queue_entry_listener_name", keys := [{ column := "listener_name" }] },
    .createIndex "queue_entry" { name := "idx_queue_entry_project_id", keys := [{ column := "project_id" }] },
    .createIndex "queue_entry" { name := "idx_queue_entry_issue_id", keys := [{ column := "issue_id" }] },
    .createIndex "task" { name := "idx_task_created_at_id", keys := [{ column := "created_at", direction := .desc }, { column := "id", direction := .desc }] },
    .createIndex "task" { name := "idx_task_status", keys := [{ column := "status" }] },
    .createIndex "task" { name := "idx_task_series", keys := [{ column := "series" }] },
    .createIndex "task" { name := "idx_task_issue_id", keys := [{ column := "issue_id" }] },
    .createIndex "usage_window" { name := "idx_usage_window_backend_label_id", keys := [{ column := "backend" }, { column := "label" }, { column := "id" }] }
  ]

end Orchestra.Store.Migrations
